### PR TITLE
Behavior trait

### LINKED ISSUE #212: No way to get the current value of a BehaviorSubject
In Rxjs there's the `getValue()` method that retries the value currently in the subject. There's no such method for rxRust's `BehaviorSubject`

### PR DESCRIPTION
**Pull request by aggalex**
This pull request introduces the `Behavior` trait, which allows the implementor's contents to be peekable using its own reference pointer. The trait is implemented by `LocalBehaviorSubject` and `SharedBehaviorSubject` accordingly. The Behavior trait is documented to include an example use.

resolves #212

### CODE REVIEW

**Comment by aggalex** [comment]
I've encountered an issue with this implementation. Consider the following two uses of a `LocalBehaviorSubject::<i32>` called `subject`:

```rust
let value = *subject.peek() + 1;
subject.clone().next(value);
```

This one works absolutely fine, the Ref returned by the subject is dropped appropriately after the first statement, and the new value is used to announce the change to all the subscribers

```rust
subject.clone().next({
    *subject.peek() + 1
});
```

This one **panics** cause the `Ref` from `peek` is not yet released before the call of the `next` method, and because the `next` method uses the data inside the RefCell mutably, it panics with a `BorrowMutError`

Something similar could happen with `SharedBehaviorSubject::<i32>`, except but it wouldn't panic but would enter a deadlock, because the mutexguard would not be released before the mutation attempt, but the release of the guard would have to wait until the statement is executed and the guard gets dropped, which practically waits for the mutation.

I'm not sure if this is up to standard, cause using the methods together like this should be fearless, in the spirit of Rust. Here are some solutions I would propose:

1. Peek should clone the contents, since it already clones it for every subscription.
2. For convenience and to avoid needless clones, there should be a `next_by` method or something similar, where the user will be able to provide a closure that returns the next item of the behavior, in relation to the current value. It's signature would be something like the following:
```rust
fn next_by(mut self, f: Fn(Self::Item) -> Self::Item)
```
And it could be used like this, in the context of the examples discussed above:
```rust
subject.clone().next_by(|n| n + 1);
```

**Comment by M-Adoo** [comment]
@aggalex  Thanks . I'll  try to merge this pr after https://github.com/rxRust/rxRust/tree/refactor-traits merged

**Comment by M-Adoo** [comment]
@aggalex would you rebase master and reimplement ?

**Comment by aggalex** [comment]
Yes, tomorrow. I'm currently on a trip.

**Comment by aggalex** [comment]
> @aggalex would you rebase master and reimplement ?

Yes, tomorrow. I'm currently on a trip.

**Review by M-Adoo — COMMENTED** [review]
Great! Would you update the `CHANGELOG.md`?

**Review by M-Adoo — APPROVED** [review]

**Review by sologeek — APPROVED** [review]

**Pull request merged**
