### PR TITLE
Propagate error & complete to group_by groups

### PR DESCRIPTION
**Pull request by AntonOellerer**
Due to an oversight during implementation, `error` and `complete` signals did not get forwarded to the `observables` emitted by the `group_by` operation.
This commit fixes this, iterating through all stored `subjects` of the operator on completion/error.

### CODE REVIEW

**Comment by AntonOellerer** [comment]
I am not entirely sure whether it is correct to immediately call `self.observer.complete()` after sending the signal to the observers, or whether we need to keep track of the observables, and only call `self.observer.complete()` when all of them have completed

**Comment by AntonOellerer** [comment]
I managed to create a test case confirming my suspicions:
```Rust
  #[cfg(not(target_arch = "wasm32"))]
  #[test]
  fn only_completes_when_all_done() {
    let scheduler = ThreadPool::new().unwrap();
    let sum = MutArc::own(0);
    let sum_c = sum.clone();
    from_iter(vec![0, 1])
      .group_by(|v| *v)
      .flat_map(move |group| group.subscribe_on(scheduler.clone()))
      .into_shared()
      .subscribe(move |v| {
        *sum_c.rc_deref_mut() += v;
      });
    thread::sleep(Duration::from_secs(1));
    assert_eq!(*sum.rc_deref(), 1);
  }
```
It does not get introduced by this fix, so I don't know, whether this is the correct place to put this

**Comment by AntonOellerer** [comment]
On further inspection, the problem might be a broader issue on communication between different threads, I will continue looking into it

**Comment by AntonOellerer** [comment]
The issue might be that `group` invokes `observer.next()` before `.subscribe()` is able to subscribe to it

**Comment by M-Adoo** [comment]
> On further inspection, the problem might be a broader issue on communication between different threads, I will continue looking into it

Fix looks good to me ,  i  think not emit `error`/`complete`  not relate to threads.  Do you have more details ?

**Comment by AntonOellerer** [comment]
I will look into it today

**Comment by AntonOellerer** [comment]
What I think is happening:
1. `Thread A`:  `group_by` emits a `subject` to the `flat_map` ([group_by.rs#L63](https://github.com/rxRust/rxRust/blob/0ddd72cb2ae902c26dee806770add0a9993a7097/src/ops/group_by.rs#L63))
2. `Thread A`: `flat_map` requests to subscribe to `subject` ([flatten.rs#188](https://github.com/rxRust/rxRust/blob/0ddd72cb2ae902c26dee806770add0a9993a7097/src/ops/flatten.rs#L188))
2. `Thread A`: `group_by` emits value to `subject` ([group_by.rs#L66](https://github.com/rxRust/rxRust/blob/0ddd72cb2ae902c26dee806770add0a9993a7097/src/ops/group_by.rs#L66))
3. `Thread A`: `Subject` scans its list of `observers` which is still empty, discards value ([subject.rs#L234](https://github.com/rxRust/rxRust/blob/0ddd72cb2ae902c26dee806770add0a9993a7097/src/subject.rs#L234))
4. `Thread B`: `InnerSubject` adds the `flat_map` to the `observers` list ([subject.rs#L281](https://github.com/rxRust/rxRust/blob/0ddd72cb2ae902c26dee806770add0a9993a7097/src/subject.rs#L281))

The reason the test case is green sometimes is when a context switch from `Thread A` to `Thread B` happens, and by this moving `step 5` to after `step 2` but before `step 4`

**Comment by M-Adoo** [comment]
Base on your provide information,  i guess that because `subscribe_on`  sometimes not subscribe immediately,  that depends on its scheduler. So it maybe miss the hot value.

I think it's a bug of  `subscribe_on`. We need to subscribe to upstream immediately and proxy the value to scheduler.  it's all based on guesswork and I'm sorry I didn't deep into debug it. I'm so busy this month.

**Comment by AntonOellerer** [comment]
Thank you for the insights, and don't worry about being busy, I will find my way around sooner or later :)

**Comment by AntonOellerer** [comment]
This can be merged I think btw

**Review by M-Adoo — APPROVED** [review]

**Pull request merged**
