### PR TITLE
Add operator 'StartWith'

### PR DESCRIPTION
**Pull request by utilForever**
This revisions includes:
- Add operator 'StartWith' (See http://reactivex.io/documentation/operators/startwith.html)
  - Create struct 'StartWithOp'
  - Add function 'start_with()'

### CODE REVIEW

**Review by M-Adoo — COMMENTED** [review]
Thanks, it's looks good to me. And for implement local and shared observable, do you think macro `impl_local_shared_both` is a better choice?

**Comment by utilForever** [comment]
@M-Adoo Okay, I'll try it right now. 😉

**Comment by utilForever** [comment]
@M-Adoo I checked `cargo fmt` and `cargo clippy` and saw no warning and error. Could you re-run it? ⛏️

**Review by M-Adoo — APPROVED** [review]
@utilForever  seems ci network error, I'll rerun it.

**Pull request merged**
