### PR TITLE
Mergify: configuration update

### PR DESCRIPTION
**Pull request by M-Adoo**
This change has been made by @M-Adoo from https://mergify.io simulator.

---

<details>
<summary>Mergify commands and options</summary>
<br />
More conditions and actions can be found in the [documention](https://doc.mergify.io/).
<br />
<br />
You can also trigger Mergify actions by commenting on this pull request:

- `@Mergifyio refresh` will re-evaluate the rules
- `@Mergifyio rebase` will rebase this PR
- `@Mergifyio backports <destination>` will backport this PR on `<destination>` branch

Additionally, on Mergify [dashboard](https://dashboard.mergify.io/) you can:

- look at your merge queues
- generate the Mergify configuration with the simulator.

Finally, you can contact us on https://mergify.io/
</details>

### CODE REVIEW

**Comment by M-Adoo** [comment]
@Mergify rebase

**Comment by M-Adoo** [comment]
@Mergifyio rebase

**Comment by Mnwa** [comment]
Hey! Can Mergify automatic update branch if it out-of-date and have not conflicts?

**Comment by M-Adoo** [comment]
I'm also using Mergify for the first time. But Mergify documents say `@Mergifyio rebase` can work. I'll try Mergify in this project.

**Pull request merged**
