### PR TITLE
feat: added `timestamp` support

### PR DESCRIPTION
**Pull request by dspasojevic**

### CODE REVIEW

**Review by wjian23 — DISMISSED** [review]

**Comment by dspasojevic** [comment]
I'll action clippy's suggestions.

I wasn't sure whether it would be preferable to introduce a new `TimestampOp` type for this or re-use the existing `MapOp`. Is there some benefit when it comes to inspecting the structure of the observable in the first approach?

**Comment by M-Adoo** [comment]
> I'll action clippy's suggestions.
> 
> I wasn't sure whether it would be preferable to introduce a new `TimestampOp` type for this or re-use the existing `MapOp`. Is there some benefit when it comes to inspecting the structure of the observable in the first approach?

You just  need introduce a type alias `type TimestampOp<...> = MapOp<....>`.

**Comment by dspasojevic** [comment]
@M-Adoo yep, understood and done. I meant whether it was better to introduce the new `Op` type and all the associated machinery including the `Observer` implementation or do what I did and piggy back off `map`.

**Comment by M-Adoo** [comment]
@dspasojevic I like your implementation, if an existing `Op` does the job well, we should use it.

 Please squash your commits.

**Review by M-Adoo — APPROVED** [review]

**Comment by dspasojevic** [comment]
@M-Adoo I've run each of the commands in the github action locally and they seem good now. Sorry about this back and forwards.

**Review by M-Adoo — APPROVED** [review]
Thanks!

**Review by wjian23 — APPROVED** [review]

**Pull request merged**
