### PR TITLE
Refactor observable trait

### PR DESCRIPTION
**Pull request by M-Adoo**
Follow #68 ,  rename RawSubscribable to Observable, and change the trait define 
from
```rust
pub trait RawSubscribable<Subscriber> {
  type Unsub: SubscriptionLike + 'static;
  fn raw_subscribe(self, subscriber: Subscriber) -> Self::Unsub;
}
```
to
```rust
pub trait Observable<O, U: SubscriptionLike> {
  type Unsub: SubscriptionLike + 'static;
  fn actual_subscribe(self, subscriber: Subscriber<O, U>) -> Self::Unsub;
}
```

### CODE REVIEW

**Comment by M-Adoo** [comment]
@helgoboss  we should finish this pr first. I give an init commit and commented many mod, see the lib.rs. We can tell other which mod you want to resolve to avoid conflict. And we sync our code across branch `refactor-observable-trait`.

**Comment by M-Adoo** [comment]
I'm working on observable creating functions.

**Comment by M-Adoo** [comment]
@helgoboss please review this pr if you have time.

**Comment by helgoboss** [comment]
@M-Adoo Okay, I will have a coffee and get to it :) Even I was hoping we could get rid of the observer 
 as type parameter of Observable (see [my comment](https://github.com/rxRust/rxRust/issues/62#issuecomment-582967482)), 
this looks like a good improvement already 😃

**Pull request merged**
