### PR TITLE
Add take_until operator

### PR DESCRIPTION
**Pull request by helgoboss**
@M-Adoo Is it okay to just provide a single-threaded version of the operator for now?

### CODE REVIEW

**Comment by M-Adoo** [comment]
Do you need any help to support a multi-thread version ？

**Comment by helgoboss** [comment]
> Do you need any help to support a multi-thread version ？

Thank you! I can try alone first but it's possible that I will need your help. Probably I can't work on this for the next 2 weeks though, so this has to wait a little bit.

**Comment by M-Adoo** [comment]
Feel free to leave me a comment if you need

**Comment by helgoboss** [comment]
@M-Adoo I hope that's it. Please have a look, thanks.

**Comment by M-Adoo** [comment]
And update change log please.

**Comment by helgoboss** [comment]
Applied the requested changes.

**Pull request merged**
