### PR TITLE
Merge public local & shared version trait into one

### PR DESCRIPTION
**Pull request by M-Adoo**
This is a big refactor for `rxRust`, almost reimplement everything and many api was broken. Use a simpler and more directly way to implement.

For the user not implement custom operator.
- 🧨 Change the behavior of `skip_while` and `skip_until` to be consistent with the [reactivex.io]()
- 🧨 the recursive emit value in `Subject` will panic, you can't recursive emit value for subject in its subscribe callback.
- 🧨  removed the `shared` mod, so there isn't `into_shared` methods anymore. If an operator or observable have different implement between local thread and multi threads, the type name for multi threads will appends suffix with `Threads`, and methods will append_with `_threads`. For example the `SubjectThreads` is the cross threads version of `Subject`, and the `.merge_threads()` is to chain the cross threads version of the `.merge()`.
- 🧨 `.subscribe` is the only way to consume the observable. `.subscribe_all` `subscribe_err` `subscribe_complete` has been removed. To reactive to the error and complete, use  `on_error` and `on_complete` operators.

To implement custom operator or scheduler.

- 🧨 `LocalObservable` and `SharedObservable` has been removed. Directly implement Observable.
- 🧨 `LocalScheduler` and `SharedScheduler` has been removed, add `Scheduler` to do same thing, and change the methods behavior.
- 🧨 `Observer` use `Item` `Err` generic type instead of associated type.

### CODE REVIEW

**Comment by M-Adoo** [comment]
@utilForever do you want to review？ of course if you have time.

**Comment by utilForever** [comment]
@M-Adoo Of course! I'll review it within several days. 😄

**Comment by M-Adoo** [comment]
> @M-Adoo Is this review something you do with the maintainer in mind?

I'm a little confused, do you mean what are the key points of the review?

**Comment by utilForever** [comment]
> > @M-Adoo Is this review something you do with the maintainer in mind?
> 
> I'm a little confused, do you mean what are the key points of the review?

I'm sorry. Never mind. 🙏

**Review by wjian23 — APPROVED** [review]

**Review by sologeek — APPROVED** [review]

**Review by utilForever — COMMENTED** [review]
It changes many code. I'm going to look at it in a few parts.

**Pull request merged**
