### PR TITLE
Add bench for filter

### PR DESCRIPTION
**Pull request by godhand4826**
Will adding bench mark testing helpful for **missing_features.md/Workflows/ci/benchmark**?

### CODE REVIEW

**Comment by M-Adoo** [comment]
@mergifyio rebase

**Review by M-Adoo — DISMISSED** [review]
Of course, and work with a benchmark report ci should be very useful.

**Comment by M-Adoo** [comment]
Would you rebase to squash  your commit ?

**Comment by godhand4826** [comment]
Sure!

**Comment by godhand4826** [comment]
Done~

**Pull request merged**
