### PR TITLE
Only subscribe to source once

### PR DESCRIPTION
**Pull request by AntonOellerer**
This PR attempts to fix the issue mentioned in #201, but unfortunatly there is a type error still in there I have not been able to fix so far.

### CODE REVIEW

**Comment by AntonOellerer** [comment]
Ah, I should have spotted this earlier :facepalm: 
Thank you in any case, this saves me a lot of hassle, I hope I can continue work tomorrow.

I did not have time to look into it yet, what is the difference between `Subject` and `BehaviorSubject`?

**Comment by AntonOellerer** [comment]
I now implemented a first prototype, but I am now struggling over another problem:
What type does `Item` assume when `impl<Source, Discr, Key> Observable for GroupByOp<Source, Discr>`?
I do not know the type of `Subject` that will be returned at compile time.

**Comment by AntonOellerer** [comment]
I am currently encountering the problem that I don't know the exact type of the `Item` when implementing `Observable` for the `GroupByOp` (as it can either be `LocalSubject` or `SharedSubject`, do you have an idea of how to solve this?

**Comment by AntonOellerer** [comment]
Ok, the way I see it, there is a fundamental problem when implementing this as is, resulting from the definition of the operator, the architecture of the library, and Rust:
The creation of new value sources in the `group_by` operator requires us to "cross" the downstream operator chaining with the upstream subscribing.
Employing the `Subjects` to act as both `observer` and `observable` takes away a lot of the hassle around reading and writing to the "operator node" from multiple points of entry, but it nevertheless requires us to know what kind of scheduling will be done for the stream. (Do we return `LocalSubject` or `SharedSubject` from the `.group_by(...)` method)?
The return value can not be an `Observable` trait object, as `Observable` is sized, and deferring the decision to another struct only starts the chain of problems anew.
For now, I do not really know how to solve this without changing the interface in a backwards-incompatible manner.
Do you have any idea?
Best regards
Anton

**Comment by AntonOellerer** [comment]
Hey :)
Sorry for all the spam!
I finished the reimplementation in the limits of my ability.
The operator works as expected, but I was not able to fix the problems without breaking the interface, meaning that
the type of subject to emit now has to be defined when calling the `group_by` method.
Maybe you can find a way to work around this, but I have no idea how to do this, and I need to move on with my thesis.
Thank you very much for your support and this fantastic library, it is really an impressive feat of software engineering, and I learned a lot working with it.
Best regards and enjoy the winter holidays!
Anton

**Comment by M-Adoo** [comment]
> Hey :) Sorry for all the spam! I finished the reimplementation in the limits of my ability. The operator works as expected, but I was not able to fix the problems without breaking the interface, meaning that the type of subject to emit now has to be defined when calling the `group_by` method. Maybe you can find a way to work around this, but I have no idea how to do this, and I need to move on with my thesis. Thank you very much for your support and this fantastic library, it is really an impressive feat of software engineering, and I learned a lot working with it. Best regards and enjoy the winter holidays! Anton

@AntonOellerer  thanks,  you've almost done everything!  Not breaking the interface is easy,  just add generic type but not add parameter.   I pushed a  commit on this pr.  Would you like to rebase and clean the git history?

**Comment by AntonOellerer** [comment]
Amazing, I don't know how this works, but thank you very much!
I rebased and cleaned the history now :)

**Review by M-Adoo — APPROVED** [review]
Thanks!

**Pull request merged**
