### PR TITLE
feat: add a RAII implementation of subscription

### PR DESCRIPTION
**Pull request by M-Adoo**
Add a RAII implementation of subscription named SubscriptionGuard. Now `subscribe`, `subscribe_err`, `subscribe_complete` and `subscribe_all` return SubscriptionGuard.

BREAKING CHANGE: subscribe by those method will auto unsubscribe when SubscriptionGuard over its scope.

### CODE REVIEW

**Comment by M-Adoo** [comment]
@helgoboss do you have time to review these code?

**Comment by helgoboss** [comment]
> @helgoboss do you have time to review these code?

Doing it now

**Comment by M-Adoo** [comment]
Good idea, or `guard_wrap`. We should find a better name with the user context.
```rust
let guard = observable
  .subscribe(...)
  .unsubscribe_when_out_of_scope();

let guard = observable
  .subscribe(...)
  .guard_wrap();
```

**Comment by helgoboss** [comment]
@M-Adoo Should I try implementing `guard_wrap()` or are you on it?

**Comment by M-Adoo** [comment]
> @M-Adoo Should I try implementing `guard_wrap()` or are you on it?

I'm glad you can finish this pr.  I'm work on #73 now. Do you have better name?

**Comment by helgoboss** [comment]
> > @M-Adoo Should I try implementing `guard_wrap()` or are you on it?
> 
> I'm glad you can finish this pr. I'm work on #73 now. Do you have better name?

Okay, I'll give it a go. How about `unsubscribe_when_dropped()`? That expressed the intent (rather than the technical implementation via guard) and is shorter than `unsubscribe_when_out_of_scope()`.

**Comment by M-Adoo** [comment]
that looks good to me.

**Comment by helgoboss** [comment]
Should I open a new pull request? Because I don't have write access to this repository. Here's the branch with `unsubscribe_when_dropped()`: https://github.com/helgoboss/rxRust/tree/feat-raii-subscription

**Comment by M-Adoo** [comment]
Yes, a  new pr please.

**Pull request merged**
